[build]
    command = "npm run build" # how to trigger a buil
    publish = "/build"



[[redirects]]
    from = "/*" # redirect any path
    to = "/index.html" # to this html page
    status = 200 # with this status
